### PR TITLE
Windows support for hover

### PR DESCRIPTION
**Pull request by karino2**
I think your PR #133 for main go-langserver is similar to what I'm investigating.
So I want to talk to you for this issue (This PR is not intended to pull-ed, but for communication purpose).

I develop some monaco based editor and integrate to go-langserver, and want to make it work on WIndows environment.

My editor send message to LS something like following:
`
{"jsonrpc":"2.0","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///d%3A/go/src/github.com/karino2/editbook/main.go"},"position":{"line":27,"character":11}},"id":1}
`
which works for tsserver.

In your PR, this message still seems fail, and I've confirmed that my changes of this PR fix the problem.
But I don't understand your changes yet.
So, my question is, your PR is...

1. Try to solve the same problem, but my input uri is wrong
2. Try to solve the same problem,  but your fix missed some cases
3. Try to solve different problem

### CODE REVIEW

**Comment by alexsaveliev** [comment]
Hey, @karino2 

Yeah, my goal is the pretty much the same as yours - I'd like to make go-langserver work on Windows (integrated into vscode). 

Here are few points I'm trying to take into account:
- I want to keep go-langserver working properly in "standalone" mode, when all the data is fetched from local file system and Sourcegraph-specific VFS mode (when LSP client is responsible for providing content of the files). In first case LSP client sends `initialize` request with `file:///tmp/foo/bar` or `file:///d%3a/foo/bar` root path while in the second `initialize` sends `file:///` root path (Sourcegraph-specific) and then all requests and responses operate with paths/URIs relative to `/` root path. So there is a need to support local FS on Unix, VFS on Unix, local FS on Windows, VFS on Windows. First two cases were already implemented.
- My PR relies on unmerged sourcegraph/ctxvfs#4 which unifies read operations from the local FS so read from `/C:/foo/bar` works

Your input URI seems correct, the same way vscode sends them.

If go-langserver tests are passing on Windows with your changes, then feel free to submit a pull request

**Comment by karino2** [comment]
Thank you.
Could you help me how to run these tests?

1. Checkout following branch: https://github.com/alexsaveliev/go-langserver/tree/windows in Windows 8.1 environment.
2. cd go-lngserver/langserver
3. go test

Then following error shown:
`
PS D:\go\src\github.com\sourcegraph\go-langserver\langserver> go test
--- FAIL: TestIntegration_FileSystem (0.09s)
    --- FAIL: TestIntegration_FileSystem/hover-a.go:1:17 (0.00s)
        langserver_test.go:1051: jsonrpc2: code 0 message: open \C:\Users\_\AppData\Local\Temp\langserver-go-integration517697819\gopath\src\test\p\a.go: The filename, directory name, or volume label syntax is incorrect.
    --- FAIL: TestIntegration_FileSystem/hover-b.go:1:20 (0.00s)
        langserver_test.go:1051: jsonrpc2: code 0 message: open \C:\Users\_\AppData\Local\Temp\langserver-go-integration517697819\gopath\src\test\p\b.go: The filename, directory name, or volume label syntax is incorrect.
    --- FAIL: TestIntegration_FileSystem/hover-p2-c.go:1:40 (0.00s)
        langserver_test.go:1051: jsonrpc2: code 0 message: open \C:\Users\_\AppData\Local\Temp\langserver-go-integration517697819\gopath\src\test\p\p2\c.go: The filename, directory name, or volume label syntax is incorrect.
    --- FAIL: TestIntegration_FileSystem/hover-b.go:1:20#01 (0.00s)
        langserver_test.go:1051: jsonrpc2: code 0 message: open \C:\Users\_\AppData\Local\Temp\langserver-go-integration517697819\gopath\src\test\p\b.go: The filename, directory name, or volume label syntax is incorrect.
    --- FAIL: TestIntegration_FileSystem/hover-p2-c.go:1:40#01 (0.00s)
        langserver_test.go:1051: jsonrpc2: code 0 message: open \C:\Users\_\AppData\Local\Temp\langserver-go-integration517697819\gopath\src\test\p\p2\c.go: The filename, directory name, or volume label syntax is incorrect.
FAIL
exit status 1
FAIL    github.com/sourcegraph/go-langserver/langserver 1.065s
`

I guess this must pass, so where I made a mistake?

**Comment by alexsaveliev** [comment]
Please checkout `%GOPATH%/src/github.com/sourcegraph/ctxcvs` from `https://github.com/alexsaveliev/ctxvfs/tree/windows` and run tests again.

This is sourcegraph/ctxvfs#4 which required to make tests pass and code work on Windows

**Comment by karino2** [comment]
Thanks! Now test is pass but my problem is not solved!
I start investigating my problem on your code base.

**Comment by alexsaveliev** [comment]
I just tried to run it locally and it doesn't work for me as well when using from vscode, errors like
```
[Error - 21:03:59] Request textDocument/hover failed.
  Message: import "/c%3A/projects/go/src/github.com/zmb3/gogetdoc": cannot import absolute path
  Code: 0 
```

I'll try to see what goes on there tomorrow and let you know

**Comment by karino2** [comment]
Oh, really?
Then, I wait your investigation for a while :-)
My change (origin of this PR) might help you.

**Comment by alexsaveliev** [comment]
Ok, sorry, my bad - there was a broken code in one local package. Actually go-langserver works for me (TM) :smile: 
I'm using vscode and https://github.com/sourcegraph/vscode-sourcegraph/tree/featuring-parity extension
My command line is `langserver-go.exe -addr :2089 -mode tcp`
Here are few messages sentbetween vscode and LSP server

```
--> request #0: initialize: {"processId":12492,"rootPath":"c:\\projects\\go\\src
\\github.com\\zmb3\\gogetdoc","capabilities":{},"trace":"off"}
<-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"hoverProvider"
:true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvide
r":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbol
Provider":true,"documentFormattingProvider":true,"xworkspaceReferencesProvider":
true,"xdefinitionProvider":true}}
...
--> request #3: textDocument/hover: {"textDocument":{"uri":"file:///c%3A/project
s/go/src/github.com/zmb3/gogetdoc/ident.go"},"position":{"line":40,"character":2
3}}
<-- result #3: textDocument/hover: {"contents":[{"language":"go","value":"type N
ode interface{End() Pos; Pos() Pos}"},{"language":"markdown","value":"----------
------------------------------------------------------------------ Interfaces \n
\nThere are 3 main classes of nodes: Expressions and type nodes, statement nodes
, and declaration nodes. The node names usually match the corresponding Go spec
production names to which they correspond. The node fields correspond to the ind
ividual parts of the respective productions. \n\nAll nodes contain position info
rmation marking the beginning of the corresponding source text segment; it is ac
cessible via the Pos accessor method. Nodes may contain additional position info
 for language constructs where comments may be found between parts of the constr
uct (typically any larger, parenthesized subpart). That position information is
needed to properly position comments when printing the construct. All node types
 implement the Node interface. \n\n"}],"range":{"start":{"line":40,"character":2
2},"end":{"line":40,"character":26}}}
```

You may enable tracing of requests/responses with `-trace` command line argument, see also `-logfile file`

Is there anything in your logs? Any errors? Could you please show messages exchange between your editor and LSP server?

**Comment by karino2** [comment]
Thank you for your information.
Your log seems almost the same as mine.
Here is my trace.

`--> request #1: textDocument/hover: {"textDocument":{"uri":"file:///d%3A/go/src/github.com/karino2/editbook/main.go"},"position":{"line":27,"character":29}}
<-- error #1: textDocument/hover: {"code":0,"message":"import \"/d%3A/go/src/github.com/karino2/editbook\": cannot import absolute path","data":null}
`
I'll investigate more.

**Comment by karino2** [comment]
My initialization seems a little different.

`
--> request #0: initialize: {"capabilities":{"textDocument":{"completion":{"comptetionItem":{"snippetSupport":true}},"synchronization":{"didSave":true,"willSave":true,"willSaveWaitUntil":true}}},"rootPath":"file:///D:/go/src","rootUri":"file:///D:/go/src"}
<-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"documentFormattingProvider":true,"xworkspaceReferencesProvider":true,"xdefinitionProvider":true,"xworkspaceSymbolByProperties":true}}
`

**Comment by alexsaveliev** [comment]
What is the hash you are using? Is it d9a06a5a3b59d6a0aad88ee1734aaa9551752dd1 or f15a63ace4857970d95ecfe9bafbae3917dd91b2? It seems that the later has this problem while d9a06a5a3b59d6a0aad88ee1734aaa9551752dd1 works. Note that main file location and exe name were changed

**Comment by karino2** [comment]
I use d9a06a5 for go-langserver (if there is no stale binary).

**Comment by alexsaveliev** [comment]
Your `rootPath` looks suspicious, I'd expect it to be repository root (for example `file:///d%3A/go/src/github.com/karino2/editbook` but not `file:///d%3A/go/src/`)

Could you try to open a folder (if there is such a functionality in your editor) that contains single repository with Go project? (D:/go/src/github.com/karino2/editbook I suppose)

**Comment by alexsaveliev** [comment]
Also, could you please print values of pkgDir, srcDir, pkgDir, srcDir in `build_context.go` after :
```
importPath := utils.PathTrimPrefix(pkgDir, srcDir)
```
Problem might be here

**Comment by karino2** [comment]
I remove rootUri, hard code rootPath, logging pkgDir and srcDir.
`
--> request #0: initialize: {"capabilities":{"textDocument":{"completion":{"comptetionItem":{"snippetSupport":true}},"synchronization":{"didSave":true,"willSave":true,"willSaveWaitUntil":true}}},"rootPath":"d:\\go\\src\\github.com\\karino2\\editbook"}
<-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"documentFormattingProvider":true,"xworkspaceReferencesProvider":true,"xdefinitionProvider":true,"xworkspaceSymbolByProperties":true}}
--> request #1: textDocument/hover: {"textDocument":{"uri":"file:///d%3A/go/src/github.com/karino2/editbook/main.go"},"position":{"line":27,"character":11}}
LOGGING /d%3A/go/src/github.com/karino2/editbook, src
<-- error #1: textDocument/hover: {"code":0,"message":"import \"/d%3A/go/src/github.com/karino2/editbook\": cannot import absolute path","data":null}`

so, pkgDir seems "/d%3A/go/src/github.com/karino2/editbook", while srcDir is "src".
Also, importPath is "/d%3A/go/src/github.com/karino2/editbook".

**Comment by alexsaveliev** [comment]
Please also make sure `GOPATH` is set, if `srcDir` is `src` it looks like `GOPATH` env is not set or set incorrectly somehow.
Print values of `gopath` inside		
```
for _, gopath := range gopaths {
```
in the same file

**Comment by karino2** [comment]
By the way, the link you specified seems dead link: https://github.com/sourcegraph/vscode-sourcegraph/tree/featuring-parity . 
Could you give me correct url?

**Comment by alexsaveliev** [comment]
> By the way, the link you specified seems dead link:

Sorry, it's a private repo, didn't knew :(

**Comment by karino2** [comment]
OK.

> 		for _, gopath := range gopaths {
>			log.Printf("gopath %s\n", gopath)

the result is

`gopath D:\go`

Seems correct.

**Comment by karino2** [comment]
I put following code in the last line of PathHasPrefix

> 	log.Printf("s, prefix, prefixSlash = %s, %s, %s", s, prefix, prefixSlash)

The result is: 

`s, prefix, prefixSlash = /d%3A/go/src/github.com/karino2/editbook, /D:/go, /D:/go/`

**Comment by alexsaveliev** [comment]
okay, I definitely need a timeout to investigate this issue. I'll keep you informed. Sorry for the delay

**Comment by karino2** [comment]
No problem. Thank you for your support.
I'll post some comment for further investigation.

**Comment by karino2** [comment]
If I change virtualPath as following, it works.

```
 func virtualPath(path string) string {
	// Windows implementation converts path to slashes and prefixes it with slash
	path = filepath.ToSlash(path)

	volname := filepath.VolumeName(path)
	if volname == "" {
		// convert %3A to :
		comps, _ := url.Parse(path)
		path = comps.Path
		volname = filepath.VolumeName(path)
	}

	after := path[len(volname):]
	path = strings.ToLower(volname) + after
	// log.Println("path: " + path)
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}
	return path
}
```

I think root cause is drive letter capital-lower mismatch. (one is coming from env value, the other is coming from rootPath message).
But I don't know how to handle that without decoding %3A here.

Do you have any suggestion on how to fix this?

**Comment by karino2** [comment]
I saw your fix, maybe this will fix my problem, too.

https://github.com/sourcegraph/go-langserver/commit/6b63dc1

**Comment by alexsaveliev** [comment]
I have made some changes, could you please try them on your side when you'll have time?

**Comment by karino2** [comment]
Yes! It's working!
Should I close this PR now?

**Comment by alexsaveliev** [comment]
Yeah. Now I should convince somehow lead developers of go-langsever that mine changes aren't so bad as they think and then merge changes upstream.

Thanks a lot for your help!

**Comment by karino2** [comment]
I agree your change is good enough comparing to the current go-langserver code quality.
I'm looking forward to merging.
Good luck!

**Pull request closed without merging**
